name: Create and Publish Tagged Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true

jobs:
  release:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    env:
      COSIGN_EXPERIMENTAL: "true"
      COSIGN_YES: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
      - name: Check install!
        run: cosign version

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: "./"
          output-file: ./sbom-${{ github.event.inputs.tag }}.spdx.json
          format: "spdx"

      - name: Create Tag
        run: git tag ${{ github.event.inputs.tag }}

      - name: Push Tag
        run: git push origin ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: gh release create ${{ github.event.inputs.tag }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SBOM as Release Asset
        run: gh release upload ${{ github.event.inputs.tag }} *.spdx.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Release Assets
        run: |
          curl -sL -o ${{ github.event.inputs.tag }}.zip https://github.com/${{ github.repository }}/archive/${{ github.event.inputs.tag }}.zip
          curl -sL -o ${{ github.event.inputs.tag }}.tar.gz https://github.com/${{ github.repository }}/archive/${{ github.event.inputs.tag }}.tar.gz

      - name: Compute Checksums
        run: |
          echo "Checksum for ${{ github.event.inputs.tag }}.zip:"
          sha256sum ${{ github.event.inputs.tag }}.zip
          echo "Checksum for ${{ github.event.inputs.tag }}.tar.gz:"
          sha256sum ${{ github.event.inputs.tag }}.tar.gz

      - name: list content
        run: ls -l

      - name: Update Semantic Tag
        run: |
          TAG=${{ github.event.inputs.tag }}
          SEMANTIC_TAG=$(echo $TAG | grep -oP '^v\d+')
          git tag -f $SEMANTIC_TAG $TAG
          git push -f origin $SEMANTIC_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve Tag to Commit SHA
        id: resolve_tag
        run: |
          COMMIT_SHA=$(git rev-list -n 1 ${{ github.event.inputs.tag }})
          echo "Resolved commit SHA: $COMMIT_SHA"
          echo "COMMIT_SHA=$COMMIT_SHA" >> "$GITHUB_ENV"

      - name: Generate hashes
        id: set_hashes
        run: |
          # Setting the commit SHA as the value for hashes.
          echo "hashes=$COMMIT_SHA" >> "$GITHUB_OUTPUT"

  # This step calls the generic workflow to generate provenance.
  provenance:
    needs: [release]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.release.outputs.hashes }}"
      # Upload provenance to a new release
      upload-assets: true
      upload-tag-name: "${{ github.event.inputs.tag }}"
